# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=50)),
                ('body', models.TextField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
