# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='body',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
