# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('scoops_remaining', models.IntegerField(choices=[(0, 'zero'), (1, 'one')], default=0)),
            ],
        ),
    ]
