# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:04
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='title',
            field=models.CharField(max_length=255, validators=[core.validators.validate_tasty]),
        ),
    ]
